### ISSUE TITLE
Validation question

### ISSUE THREAD

**Issue by garbinmarcelo** [gcofficial/vue-repeater#6]
Hello, 
I need something like your package. I found it very interesting, but before using it I would like to know if it is possible to validate the fields with an external library, for example vee-validate.

Thank you

**Comment by gcofficial** [comment]
Hey 👋🏻
Thx for feedback. 

> I need something like your package. I found it very interesting, but before using it I would like to know if it is possible to validate the fields with an external library, for example vee-validate.

Why not? Do you have some issues with that?

**Comment by garbinmarcelo** [comment]
Hi, Sorry to have opened issue, but it is more a question than a problem. I haven't used the package yet, I would just like a confirmation before multiple input validation, but I will use it and do the necessary tests then.

Thanks for the answer.

**Comment by gcofficial** [comment]
@garbinmarcelo Sure. No problem and thx for feedback 👍
